### Read game map background
# @name game_map_background
@gameId=game123
GET {{$dotenv %BASE_URL}}/{{gameId}}/map/background

### Read game map topology
# @name game_map_topology
@gameId=game123
GET {{$dotenv %BASE_URL}}/{{gameId}}/map/topology

### Read players avatars
# @name game_players_avatars
@gameId=game123
GET {{$dotenv %BASE_URL}}/{{gameId}}/players/avatar

### Create game
# @name create_game
POST {{$dotenv %BASE_URL}}
Content-Type: application/json

{
  "id": "j8gD4k",
  "players": [
    {
      "id": "aS6urW",
      "name": "Alisa",
      "color": "2F0080"
    }
  ],
  "statistics": {
    "playTime": 3600,
    "winnerId": "aS6urW"
  }
}


# game123_map_background.png



# ### Auth
# # @name acccess_token_request
# POST {{AccessTokenURL}}
# Content-Type: application/x-www-form-urlencoded

# grant_type=client_credentials
# &client_id={{DesignerApiClientID}}
# &client_secret={{DesignerApiClientSecret}}
# &scope={{DesignerApiScope}}

# ###
# @AccessToken={{acccess_token_request.response.body.access_token}}

# .env file can be used by referencing variables this way {{$dotenv %MY_VARIABLE}}